### ISSUE TITLE
I don't get it

### ISSUE THREAD

**Issue by elhoucine** [rikonor/meteor-simple-mutex#2]
Sorry don't get what the package is about. 

can you clarify things for me please ?

**Comment by rikonor** [comment]
@elhoucine Sure thing. A mutex is a mechanism to lock a resource.
Basically this attaches to whichever Mongo collection you enable it for - then you can lock individual documents using `doc.lock()`. Once a document is locked, all other clients will be unable to update it.

Let's say you have a scenario where multiple users have access to a single resource, e.g. an editable article. By using `article.lock()` one user can make sure the article will stay the same until he decides to save whatever changes he made.
